### ISSUE TITLE
[Feature Request]添加查看订阅的漫画功能

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/plugin.bilibili-manga#1]
开发者你好！
漫画阅读器和插件都很好用，但是否能添加查看订阅的漫画功能呢？比如说有一个Tab，点击即可查阅自己订阅的漫画。或者让用户自己可选是否自动同步订阅到书架。
如果可以的话，希望动漫之家插件也支持这个功能

**Comment by LancerComet** [comment]
我不太懂这个订阅的概念，现在插件漫画可以放到书架里，这个功能不行么

**Comment by Jiang10086** [comment]
> 我不太懂这个订阅的概念，现在插件漫画可以放到书架里，这个功能不行么

就是哔哩哔哩漫画中「[我的追漫](https://manga.bilibili.com/account-center/my-favourite)」，可以查看自己关注漫画的更新。希望能在阅读器中也能看到自己追更的漫画而不是需要再次手动搜索加入书架

**Comment by LancerComet** [comment]
如果是走追漫接口，这个有点 platform specific，Rulia 并不想去实现某个平台的特定功能，而是想实现一个通用型的方式，目前是通过将漫画添加到书架中的方式进行，这个功能我要考虑一下.

**Comment by SIKtt** [comment]
可以在筛选里增加已购漫画 @Jiang10086  
https://github.com/SIKtt/plugin.bilibili-manga
