### ISSUE TITLE
[Bug Report]下载的图片没有扩展名

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/plugin.bilibili-manga#2]
我搜索「[天使降临到我身边](https://manga.bilibili.com/detail/mc30466)」并下载第117话的第14页，发现下载的文件名是「14」并没有任何扩展名，之后我尝试了几部热门漫画，也是如此。希望修复

**Comment by LancerComet** [comment]
我来处理一下确保都是 JPG

**Comment by LancerComet** [comment]
APP 的代码已处理完成，0.18 发布，插件漫画将根据自身的图片类型设置对应的扩展名.

**Comment by LancerComet** [comment]
0.18 已发布.
