### ISSUE TITLE
[Bug Report]搜索结果出现无关的HTML标签文字

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/plugin.bilibili-manga#3]
![image](https://github.com/RuliaReader/plugin.bilibili-manga/assets/67213568/de7802a4-ce6a-4c46-a157-f80062251f1a)
如图，似乎接口返回里强调了搜索匹配的文字，但阅读器并没有渲染出来而是直接用纯文本表示，占据了很多空间，希望能修复

**Comment by LancerComet** [comment]
比利比利漫画返回的标签，我来过滤一下

**Comment by LancerComet** [comment]
Fixed in 0.2.0: https://github.com/RuliaReader/plugin.bilibili-manga/releases/tag/v0.2.0
