### ISSUE TITLE
[Feature Request]同步阅读记录

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/plugin.bilibili-manga#4]
希望能增加双向同步阅读记录的功能，这样就能从上次落下的地方开始看，而且iPad和Windows的进度也能同步了

**Comment by LancerComet** [comment]
这个不光要更新插件，也要更新 APP，会慢一点

**Comment by LancerComet** [comment]
App 代码已经更新完毕，现在插件可以定义一个同步阅读记录的函数，Rulia 将在打开插件漫画后调用.

**Comment by LancerComet** [comment]
Has been implemented in 0.3.0.
