### ISSUE TITLE
[Feature Request]拿到手机客户端「超清」的画质

### ISSUE THREAD

**Issue by Jiang10086** [RuliaReader/plugin.bilibili-manga#5]
以《天使降临到我身边》第117话第14页为例，手机客户端打开「超清」模式，通过抓包得知获得了一张1200px宽的图片（请求URL：https://manga.hdslb.com/bfs/manga/dfb8a8f657e5100f647aa5a9434cb60f791a6a1f.jpg@1200w.webp?token=***&ts=6603a436） 
（「***」部分为一串ID，已隐去），而网页版和该漫画插件都只得到了一张1100px宽的图片，不如手机看清晰。不知道是否能够获取手机版的图片呢？

![image](https://github.com/RuliaReader/plugin.bilibili-manga/assets/67213568/543f5536-5f8f-41c7-83f6-47f2c6692952)
![IMG_9592](https://github.com/RuliaReader/plugin.bilibili-manga/assets/67213568/0c9e4ac0-eb04-4858-81a7-501482afa336)

**Comment by LancerComet** [comment]
1100 是我自己选的，我来给插件设置里加一个画质挡位选择吧

**Comment by LancerComet** [comment]
Implemented in 0.2.0: https://github.com/RuliaReader/plugin.bilibili-manga/releases/tag/v0.2.0
