### ISSUE TITLE
路人女主的养成方法-恋爱节拍器这部B漫插件根本加载不出来，不知道是不是图片尺寸问题，老蓝能解决一下吗？

### ISSUE THREAD

**Issue by ABXCDEDG** [RuliaReader/plugin.bilibili-manga#7]
![屏幕截图 2024-11-09 230612](https://github.com/user-attachments/assets/edbf9a69-b3d6-4fb7-94a1-29141c310f77)
![屏幕截图 2024-11-09 230702](https://github.com/user-attachments/assets/1dc10b0b-7b88-4eb5-b6a4-f2b67f627e87)

**Comment by LancerComet** [comment]
#8
